{% set name = "stardist-napari" %}
{% set version = "2024.8.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d5fb082f65fd174b3d0862fb471032e0570ed4f09cc0725ceed03ab3423590d9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - magicgui >=0.4.0
    - napari >=0.4.13
    - python >={{ python_min }}
    - stardist >=0.8.3
    - tensorflow

test:
  imports:
    - stardist_napari
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://github.com/stardist/stardist-napari
  summary: the napari plugin for StarDist, a deep learning based 2D and 3D object detection method with star-convex shapes.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - maweigert
    - uschmidt83
